### ISSUE TITLE
部署后, 客户端 notifications/v2 504

### ISSUE THREAD

**Issue by mhcxp** [idoop/docker-apollo#1]
# https://github.com/ctripcorp/apollo/issues/1045

**Comment by idoop** [comment]
用的是这个镜像跑起来的吗？如果是504,检查一下网络是不是用了Bridge模式,最好用host模式.

**Comment by mhcxp** [comment]
不是host模式，但确定网络是通的。打算每个环境起一个单独的容器，host不适合

**Comment by idoop** [comment]
bridge模式做了一层NAT,因此所有进来的请求到容器这的源IP都会变成bridge网关的IP，暂时没有更好的解决办法。不过你用host模式，同样可以指定端口，在容器启动前指定相应环境好的Port即可，如要开Dev，则指定`ADMIN_DEV_PORT`和`CONFIG_DEV_PORT`就可以了。[详见Env说明](https://github.com/idoop/docker-apollo#environment-%E5%8F%82%E6%95%B0)
