### ISSUE TITLE
wiki的部署portal中部署有问题

### ISSUE THREAD

**Issue by ilanni2460** [idoop/docker-apollo#12]
wiki的部署portal中部署有问题yml文件有问题

**Comment by idoop** [comment]
@ilanni2460 哪段?请截个图看下.

**Comment by eddycjy** [comment]
请问解决了吗，本来看到这个项目打算试一下...

**Comment by idoop** [comment]
@EDDYCJY ,不知道 @ilanni2460 遇到了什么问题,但我自己用是一直没问题的.

**Comment by idoop** [comment]
@ilanni2460 关闭这个issue了,如果有需要请重开.
