### ISSUE TITLE
K8S部署了portal之后外网如何访问

### ISSUE THREAD

**Issue by zzzwt** [idoop/docker-apollo#18]
如题，K8S一直用nodeport模式能让外网访问，但是service为ClusterIP模式的话怎么来访问呢

**Comment by zzzwt** [comment]
而且portal起不来，日志看起来正常没报错，但是pod 自己crash掉了

**Comment by idoop** [comment]
你是要在集群中访问Portal还是对应的环境的config和admin服务呢？
如果是Portal，请保证Portal启动后能够连接到对应的config和admin，然后绑定相应的`service`即可访问到Portal.

**Comment by idoop** [comment]
@zzzwt 要是还有问题，请重开此issue
