### ISSUE TITLE
docker版怎么使用client 命令行 操作访问

### ISSUE THREAD

**Issue by wuzhouzhou** [idoop/docker-apollo#2]
docker版 怎么使用client 命令行 操作访问 配置文件的值 
我知道项目里面通过demo代码可以获取到 但是通过client 命令行里怎么访问呢

**Comment by idoop** [comment]
参考[Apollo客户端接入指南](https://github.com/ctripcorp/apollo/wiki/%E5%85%B6%E5%AE%83%E8%AF%AD%E8%A8%80%E5%AE%A2%E6%88%B7%E7%AB%AF%E6%8E%A5%E5%85%A5%E6%8C%87%E5%8D%97)，实际就是HTTP请求操作,用是什么语言实现的客户端都是一样的.

**Comment by wuzhouzhou** [comment]
谢谢  希望您能 继续更新 docker版的 apollo
