### ISSUE TITLE
是否可以支持jvm参数优化

### ISSUE THREAD

**Issue by zhuzw1015** [idoop/docker-apollo#21]

**Comment by zhuzw1015** [comment]
启动容器的时候如何做jvm优化，是否需要重新定义dockerfile

**Comment by idoop** [comment]
@zhuzw1015 内置启动脚本设置的参数已经在携程Apollo项目开发与生成环境运行多年了,一般是不需要动的,除非真有特殊的配置需求,否则真的不建议修改.如果要进行修改,建议在`docker-entrypoint`文件中添加修改脚本,以启动时环境变量的方式传入.

**Comment by zhuzw1015** [comment]
好的，谢谢
