### ISSUE TITLE
eureka返回内网地址,导致本地测试无法连接

### ISSUE THREAD

**Issue by dustdragonpzc** [idoop/docker-apollo#22]
你好,我这边使用你的docker镜像,采用all in one的方式部署的. 然后阿波罗的配置中心部署在外网,我本地的java客户端想访问这个外网的配置中心,然后启动的时候报错,long polling url: http://172.17.0.3:8080/notifications/v2?cluster=default&appId=dreamplaza-happymall-portal&ip=172.18.110.1&notifications=%5B%7B%22namespaceName%22%3A%22application%22%2C%22notificationId%22%3A-1%7D%5D, reason: Could not complete get operation [Cause: connect timed out],这个172.17.0.3是eureka内网地址,所以访问不到,请问下这个问题应该怎么解决

**Comment by dustdragonpzc** [comment]
https://github.com/ctripcorp/apollo/issues/1741  这个是官方那边给的解决方案,我想请教下您,如果使用您这边的镜像的话,还需要再配置什么额外的参数吗

**Comment by idoop** [comment]
@dustdragonpzc 

请参考 #20 与 [Wiki](https://github.com/idoop/docker-apollo/wiki#3%E4%BA%91%E4%B8%8A%E9%83%A8%E7%BD%B2config-%E7%BA%BF%E4%B8%8B%E9%83%A8%E7%BD%B2portal) ,

主要需要是设置与 portal 连接的那个配置实例的xxx_LB的env值, portal侧无需额外改动. 

若是有多个配置实例做负载均衡,那么只需要配置与portal连接的那个配置实例的xxx_LB的env值,其他实例无需配置.

**Comment by dustdragonpzc** [comment]
你好,我这边在DEV环境做了以下修改,
修改了 DEV 库中的ServerConfig表中的eureka.service.url 为 http://外网IP:8080/eureka/
在docker的环境变量中加入了 DEV_LB:外网IP,
解决了上面eureka为内网地址无法访问的问题,
但是现在出现了一个问题就是Portal那边连接不上了DEV环境了.
![image](https://user-images.githubusercontent.com/7151278/68000430-17be7900-fc9b-11e9-85a5-7f888d0ab61b.png)
APOLLO-CONFIGSERVICE check health 的状态是正常的
APOLLO-ADMINSERVICE check health 提示 Connection refused 
请问下这边是哪边配置出问题了

**Comment by idoop** [comment]
@dustdragonpzc 
更新了下[Wiki](https://github.com/idoop/docker-apollo/wiki#2%E5%88%86%E5%B8%83%E9%83%A8%E7%BD%B2), 里面使用例子应该还算是详尽.
你看看其中的分布式部署和云上线下部署方式,多尝试尝试就能明白了.

**Comment by idoop** [comment]
若有问题，请重新再开.
