### ISSUE TITLE
EUREKA_INSTANCE_HOME_PAGE_URL环境变量设置

### ISSUE THREAD

**Issue by micromouse** [idoop/docker-apollo#24]
我需要将adminservice和configservice的注册地址修改为主机地址，而不是缺省的docker的内网地址，以前在虚拟机CentOS中部署的时是修改startup.sh，增加
export JAVA_OPTS="$JAVA_OPTS -Deureka.instance.ip-address=192.168.1.xx -Deureka.instance.homePageUrl=http://192.168.1.xx:8080/"

请问下作者大大，这个版本有没有相关的配置，多谢！

**Comment by idoop** [comment]
@micromouse  配置对应环境的LB地址即可，比如DEV环境下就配置DEV_LB的值。详情参考Wiki的用例。

**Comment by micromouse** [comment]
@idoop 成功了，多谢！
