### ISSUE TITLE
启动之后，无法访问，且没有端口占用

### ISSUE THREAD

**Issue by tcxiaotudou** [idoop/docker-apollo#29]
Starting apollo_apollo_1 ... done
Attaching to apollo_apollo_1
apollo_1  | + portalPath=/apollo-portal
apollo_1  | + portalShellPath=/apollo-portal/scripts/startup.sh
apollo_1  | + '[' 0 == 0 ']'
apollo_1  | + [[ -n jdbc:mysql://192.168.1.96:3306/ApolloPortalDB?characterEncoding=utf8 ]]
apollo_1  | + startPortal
apollo_1  | + [[ ! -d /apollo-portal/scripts ]]
apollo_1  | + [[ -n '' ]]
apollo_1  | + [[ -n jdbc:mysql://192.168.1.96:3306/ApolloConfigDB_DEV?characterEncoding=utf8 ]]
apollo_1  | + startENV dev 'jdbc:mysql://192.168.1.96:3306/ApolloConfigDB_DEV?characterEncoding=utf8' root xy123456 8090 8080
apollo_1  | + targetENV=dev
apollo_1  | + targetDb='jdbc:mysql://192.168.1.96:3306/ApolloConfigDB_DEV?characterEncoding=utf8'
apollo_1  | + targetDbUser=root
apollo_1  | + targetDbPwd=xy123456
apollo_1  | + targetAdminPort=8090
apollo_1  | + targetConfigPort=8080
apollo_1  | + targetEnvAddr=
apollo_1  | + configPath=/apollo-config/dev
apollo_1  | + configShellPath=/apollo-config/dev/scripts/startup.sh
apollo_1  | + adminPath=/apollo-admin/dev
apollo_1  | + adminShellPath=/apollo-admin/dev/scripts/startup.sh
apollo_1  | + [[ ! -d /apollo-config/dev/scripts ]]
apollo_1  | + /apollo-config/dev/scripts/startup.sh
apollo_1  | Wed May 27 04:13:30 UTC 2020 ==== Starting ==== 
apollo_1  | Started [68]
apollo_1  | Waiting for server startup....
apollo_1  | Wed May 27 04:13:51 UTC 2020 Server started in 20 seconds!
apollo_1  | + [[ '' != [tT][rR][uU][eE] ]]
apollo_1  | + [[ ! -d /apollo-admin/dev/scripts ]]
apollo_1  | + /apollo-admin/dev/scripts/startup.sh
apollo_1  | Wed May 27 04:13:51 UTC 2020 ==== Starting ==== 
apollo_1  | Started [263]
apollo_1  | Waiting for server startup...
apollo_1  | Wed May 27 04:14:06 UTC 2020 Server started in 15 seconds!
apollo_1  | + [[ -n '' ]]
apollo_1  | + [[ -n jdbc:mysql://192.168.1.96:3306/ApolloConfigDB_FAT?characterEncoding=utf8 ]]
apollo_1  | + startENV fat 'jdbc:mysql://192.168.1.96:3306/ApolloConfigDB_FAT?characterEncoding=utf8' root xy123456 8091 8081
apollo_1  | + targetENV=fat
apollo_1  | + targetDb='jdbc:mysql://192.168.1.96:3306/ApolloConfigDB_FAT?characterEncoding=utf8'
apollo_1  | + targetDbUser=root
apollo_1  | + targetDbPwd=xy123456
apollo_1  | + targetAdminPort=8091
apollo_1  | + targetConfigPort=8081
apollo_1  | + targetEnvAddr=
apollo_1  | + configPath=/apollo-config/fat
apollo_1  | + configShellPath=/apollo-config/fat/scripts/startup.sh
apollo_1  | + adminPath=/apollo-admin/fat
apollo_1  | + adminShellPath=/apollo-admin/fat/scripts/startup.sh
apollo_1  | + [[ ! -d /apollo-config/fat/scripts ]]
apollo_1  | + /apollo-config/fat/scripts/startup.sh
apollo_1  | Wed May 27 04:14:06 UTC 2020 ==== Starting ==== 
apollo_1  | Started [410]
apollo_1  | Waiting for server startup...
apollo_1  | Wed May 27 04:14:22 UTC 2020 Server started in 15 seconds!
apollo_1  | + [[ '' != [tT][rR][uU][eE] ]]
apollo_1  | + [[ ! -d /apollo-admin/fat/scripts ]]
apollo_1  | + /apollo-admin/fat/scripts/startup.sh
apollo_1  | Wed May 27 04:14:22 UTC 2020 ==== Starting ==== 
apollo_1  | Started [599]
apollo_1  | Waiting for server startup...
apollo_1  | Wed May 27 04:14:37 UTC 2020 Server started in 15 seconds!
apollo_1  | + [[ -n '' ]]
apollo_1  | + [[ -n '' ]]
apollo_1  | + [[ -n '' ]]
apollo_1  | + [[ -n '' ]]
apollo_1  | + [[ -n jdbc:mysql://192.168.1.96:3306/ApolloPortalDB?characterEncoding=utf8 ]]
apollo_1  | + /apollo-portal/scripts/startup.sh
apollo_1  | Wed May 27 04:14:37 UTC 2020 ==== Starting ==== 
apollo_1  | Started [748]
apollo_1  | Waiting for server startup...
apollo_1  | Wed May 27 04:14:52 UTC 2020 Server started in 15 seconds!
apollo_1  | + loop=1
apollo_1  | + '[' 1 -eq 1 ']'
apollo_1  | + /usr/local/bin/healthcheck
apollo_1  | The portal service is runing.
apollo_1  | The dev admin service is runing.
apollo_1  | The dev config service is runing.
apollo_1  | The fat admin service is runing.
apollo_1  | The fat config service is runing.
apollo_1  | + sleep 300

**Comment by tcxiaotudou** [comment]
数据库（192.168.1.96）在其他机器上，不知是否会有影响？

**Comment by tcxiaotudou** [comment]
![image](https://user-images.githubusercontent.com/17454614/82977403-4ecbf180-a014-11ea-8df3-1c4c63a1fc81.png)

**Comment by Icedroid** [comment]
使用ports没有生效

**Comment by idoop** [comment]
贴一下docker-compose的内容,注意数据库地址以及账号密码请混淆或删去. 
@Icedroid @tcxiaotudou
