### ISSUE TITLE
启用[访问密钥后],客户端不加验证依然可以访问

### ISSUE THREAD

**Issue by xyyanxin** [idoop/docker-apollo#31]
使用apollo的密钥访问验证后
客户端不需要加验证,发现可以访问到.

**Comment by idoop** [comment]
@xyyanxin Apollo最开始设计时客户端接入订阅是不需要验证的,到1.6.0版本开始支持配置密钥访问,默认不开启.
详细用法请查看[官方文档](https://www.apolloconfig.com/#/zh/usage/apollo-user-guide?id=_62-%e9%85%8d%e7%bd%ae%e8%ae%bf%e9%97%ae%e5%af%86%e9%92%a5).
有Apollo的使用问题可以到官方仓库提出, 本仓库仅对服务进行容器化.
