### ISSUE TITLE
注册IP错误，导致项目获取不到真实IP

### ISSUE THREAD

**Issue by jiaoyilun** [idoop/docker-apollo#6]
K8s中部署成功，但是注册到Eureka的服务IP为容器内部IP，导致在项目中指定真是IP之后，还是连接的内部ip，连接不上，估计需要过滤网卡

**Comment by idoop** [comment]
@jiaoyilun 可以指定对应环境的LB地址为你给的IP,例: `DEV_LB: 10.10.10.10`

**Comment by jiaoyilun** [comment]
是不是需要把8080在容器里暴露出来，这个指定master: 暴露端口？

**Comment by idoop** [comment]
必须的.不暴露如何访问?就是写个service绑定一下pod就好了,参考wiki.

**Comment by jiaoyilun** [comment]
已解决，感谢
