### ISSUE TITLE
这个文件需要放到指定文件夹下吗，执行的时候出现这种错误无法打包镜像

### ISSUE THREAD

**Issue by gnsilence** [idoop/docker-apollo#8]
apollo.tar.gz         5059k --:--:-- ETA
apollo.tar.gz         5059k --:--:-- ETA
apollo.tar.gz         5059k --:--:-- ETA
apollo.tar.gz         5067k --:--:-- ETA
apollo.tar.gz         5069k --:--:-- ETA
apollo.tar.gz         5086k --:--:-- ETA
apollo.tar.gz         5086k --:--:-- ETA
apollo.tar.gz         5090k --:--:-- ETA
wget: error getting response
The command '/bin/sh -c wget ${APOLLO_URL} -O apollo.tar.gz && tar -zxf apollo.tar.gz &&     rm apollo.tar.gz && test -e apollo-${VERSION} &&     sed -e "s/db_password=/db_password=toor/g"          -e "s/^dev_meta.*/dev_meta=http:\/\/localhost:${CONFIG_DEV_PORT}/"         -e "s/^fat_meta.*/fat_meta=http:\/\/localhost:${CONFIG_FAT_PORT}/"         -e "s/^uat_meta.*/uat_meta=http:\/\/localhost:${CONFIG_UAT_PORT}/"         -e "s/^pro_meta.*/pro_meta=http:\/\/localhost:${CONFIG_PRO_PORT}/" -i apollo-${VERSION}/scripts/build.sh &&     bash apollo-${VERSION}/scripts/build.sh && rm -rf /root/.m2 &&     mkdir /apollo-admin/dev /apollo-admin/fat /apollo-admin/uat /apollo-admin/pro /apollo-config/dev /apollo-config/fat /apollo-config/uat /apollo-config/pro /apollo-portal -p &&     mv apollo-${VERSION}/apollo-portal/target/apollo-portal-${VERSION}-github.zip         apollo-${VERSION}/apollo-adminservice/target/apollo-adminservice-${VERSION}-github.zip        apollo-${VERSION}/apollo-configservice/target/apollo-configservice-${VERSION}-github.zip / &&     rm -rf apollo-${VERSION} &&     chmod +x /usr/local/bin/docker-entrypoint /usr/local/bin/healthcheck' returned a non-zero code: 1

**Comment by idoop** [comment]
`wget: error getting response`,是你的网络不好,里面的Apollo代码没下载成功.
